// swift-tools-version: 5.6

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "TheCrown",
    platforms: [
        .iOS("15.2")
    ],
    products: [
        .iOSApplication(
            name: "TheCrown",
            targets: ["AppModule"],
            bundleIdentifier: "com.audiospot.TheCrown",
            teamIdentifier: "B3GR99DULL",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .asset("AppIcon"),
            accentColor: .presetColor(.yellow),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            appCategory: .music
        )
    ],
    dependencies: [
        .package(url: "https://github.com/AudioKit/AudiokitUI", .branch("main"))
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            dependencies: [
                .product(name: "AudioKitUI", package: "audiokitui")
            ],
            path: "."
        )
    ]
)